### ISSUE TITLE
mu4e compose signature - your blog post on including images

### ISSUE THREAD

**Issue by Abu-Daud** [cesarolea/emacs#1]
Hello, thank you for your blogpost
[(https://blog.cesarolea.com/posts/html-signatures-with-mu4e/index.html)]
I still don't understand how to do a simple 

`<a href="myspace.com">My Cool Site</a>`
or
` <a href="myspace.com">my_logo.png</a>`
inside of the /emacs.d/init.el
or the .spacemacs

I think there is a way to escape some of the html chars inside of the elisp that I don't understand yet.  
Thank you if you could expand your post just a bit.

```
 ( mu4e-compose-signature  .
                        (concat
                         "Tom\n"
                         "www.Tom.com\n"))))
```

**Comment by cesarolea** [comment]
> Hello, thank you for your blogpost [(https://blog.cesarolea.com/posts/html-signatures-with-mu4e/index.html)] I still don't understand how to do a simple
> 
> `<a href="myspace.com">My Cool Site</a>` or ` <a href="myspace.com">my_logo.png</a>` inside of the /emacs.d/init.el or the .spacemacs
> 
> I think there is a way to escape some of the html chars inside of the elisp that I don't understand yet. Thank you if you could expand your post just a bit.
> 
> ```
>  ( mu4e-compose-signature  .
>                         (concat
>                          "Tom\n"
>                          "www.Tom.com\n"))))
> ```

Try wrapping your HTML in `<#part type=text/html><#/part>` tags. So for example

```
(mu4e-compose-signature . "<#part type=text/html><a href="myspace.com">My Cool Site</a><#/part>")
```

Then before you send your email call `org-mime-htmlize`. Try it first without external images, especially if you are working with GMail.

**Comment by Abu-Daud** [comment]
Thank you. I think that's the missing piece.
________________________________
